### ISSUE TITLE
issue about autoincreamental ids

### ISSUE THREAD

**Issue by lingzhang-lyon** [robertcao/CMPE275_Project2#1]
current version using count +1,

but if deleted one item (not the last one) , then add a new item will create duplicate ids
for example, if already have 6 item, then delete no.5
then add a new item, the id would also be 6  (already exist)

**Comment by pat2013** [comment]
u can add my genuuid method to assign unique id to offer
var uuid = guid();
....
{
offer.offerId = uuid;
.}....
var guid = (function() {
  function s4() {
    return Math.floor((1 + Math.random()) \* 0x10000)
               .toString(16)
               .substring(1);
  }
  return function() {
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
           s4() + '-' + s4() + s4() + s4();
  };
})();

**Comment by lingzhang-lyon** [comment]
if use guid() method, need to change the type of  Id in models from Number To String
for example:
if we used guid() when creating offer, 
then we need to change all the id type in the models: offer, offerHistory and comment
