### ISSUE TITLE
issue about update offer

### ISSUE THREAD

**Issue by lingzhang-lyon** [robertcao/CMPE275_Project2#2]
when update an offer,  we need to provide all the information about the offer,
including the fields that you want to update and the fields that you don't want to update.

if missing some parameter(those fields are not updated), 
the fields that need to update will be updated, 
but the fields that should not be changed  will also be reset (to empty),

**Comment by pat2013** [comment]
there are 2 possible ways: 
1.u can do validation in database if the input field is empty keep old record
2.u can get all old records first then update the new records and put it back to DB. 
Maybe have a better way to do this.

**Comment by pat2013** [comment]
http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate
check this out may be a better way
